version: '3.4'

services:
  todoapp:
    image: ${DOCKER_REGISTRY-}todoapp
    build:
      context: .
      dockerfile: TodoApp/Dockerfile
    ports:
     - 8000:80

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server
    ports:
     - 1433:1433
    environment:
      SA_PASSWORD: "1"
      ACCEPT_EULA: "Y"
