version: '3.4'

networks:
  dev:
    driver: bridge 

services:
  todoapp:
    image: ${DOCKER_REGISTRY-}todoapp
    build:
      context: .
      dockerfile: TodoApp/Dockerfile
    ports:
     - 8000:80
    networks :
     - dev

  tododb:
    image: postgres

  postgreadmin:
    image: dpage/pgadmin4

volumes:
  postgres_data:
  postgreadmin_data: